CONFIG = {
    'FACEBOOK_TOKEN': 'EAAV7Og9VPQ4BAB6pjwft5uwZAhZBuRZAd83UqBQegxjvzHZANU1C2XUwDc7bdBjDoZBAZBgDo1pUrNrM14lrCZAI9oVEzUMay0wOY78DSiC0JdlcnuYkfWB68ZAiqMHZC9ayJZBPVZAqAizwCtZACdZC3ZAeDI4CoU4Jk22EwJGUbJjYbLwQZDZD',
    'VERIFY_TOKEN': 'verify_hecbot',
    'SERVER_URL': 'https://hec-bot.herokuapp.com/'
}